# Generated by Django 5.0.2 on 2024-02-09 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Members", new_name="Member",),
    ]
